### ISSUE TITLE
Compilation error for release

### ISSUE THREAD

**Issue by siargey-pisarchyk** [KleinYuan/Caffe2-iOS#16]
Debug build is ok.
But trying to build Release produses link errors:

Undefined symbols for architecture arm64:
  "cv::_InputArray::_InputArray(cv::Mat const&)", referenced from:
      caffe2::ImageInputOp<caffe2::CPUContext>::DecodeAndTransposeOnly(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned char*, int, int, std::__1::mersenne_twister_engine<unsigned int, 32ul, 624ul, 397ul, 31ul, 2567483615u, 11ul, 4294967295u, 7ul, 2636928640u, 15ul, 4022730752u, 18ul, 1812433253u>*, std::__1::bernoulli_distribution*) in libCaffe2_CPU.a(image_input_op.cc.o)

      ... other

  "cv::_OutputArray::_OutputArray(cv::Mat&)", referenced from:
      ... other

**Comment by KleinYuan** [comment]
@sergey-pisarchik 
You can fix this issue by rebuild the opencv, since this error results from `opencv` is not built correctly as static/compatible (or with a bug).

I have resolved this issue in my local branch and am planning to update a new [opencv.framework](https://github.com/KleinYuan/Caffe2-iOS/tree/master/src/caffe2-ios/caffe2-ios/opencv2.framework) to all branches (I'm travelling and thus have no access to that Mac with local branch. I will fix this immediately when I get back).

If you are in a hurry, try this:
1. Rebuild static opencv with these [steps](https://github.com/KleinYuan/Caffe2-iOS/tree/master/src/caffe2-ios/caffe2-ios/opencv2.framework)

2. However, when do you ```git clone https://github.com/opencv/opencv.git```, you are by default checkout the `master` branch, which is not guaranteed to be stable (which is why you see this error on the surface). Therefore, try to checkout to a stable released tag branch such as ```https://github.com/opencv/opencv/tree/2.4.3```, then follow the steps above

3. after build, delete the this [framework](https://github.com/KleinYuan/Caffe2-iOS/tree/master/src/caffe2-ios/caffe2-ios/opencv2.framework) and drag your new build inside instead.

4. Potentially, if you still cannot archive correctly, please post your error in here. I remember I changed the Cmake file to fix one issue while fixing this bug, but cannot recall clearly that one until I get back to check my Mac. It seems like that you need to remove this [line](https://github.com/opencv/opencv/blob/ece3fac7efb07bf01a7875d82be51a69c0d8a1c2/platforms/ios/build_framework.py#L146) while build the opencv. Try it and let me know whether it works (referring [this](https://github.com/opencv/opencv/issues/8121#issuecomment-276958174)).

**Comment by KleinYuan** [comment]
@sergey-pisarchik 

This [commit](https://github.com/KleinYuan/Caffe2-iOS/commit/e2f05754c296201e43ff52beba0231ae4d392cc1) should fix this.
Also, according to our slack chat, you resolved this issue with a correct build opencv. Therefore, I think I can close this issue.

Feel free to reopen it if you still have this problem.
