### ISSUE TITLE
Why is openCV used in here?

### ISSUE THREAD

**Issue by Shoshin23** [KleinYuan/Caffe2-iOS#9]
Hey @KleinYuan 
Great job on breaking ground here with caffe2. Your example worked perfectly well for me. I was dissecting your code and comparing it with the android version on their site and was trying to understand why did you use opencv here? Was it to preprocess the image? And was it really required? 

Also, will i need to make changes to the open cv code if I'm going to say drop style transfer models instead of squeezenet? 

Thanks!

**Comment by KleinYuan** [comment]
@Shoshin23 
Hi, glad to hear that the example works perfectly well for you.

Sorry to get you confused here and let me clarify one thing:

I put the OpenCVWrapper here as a stub for now (which means, it's not actually required and if you remove it, it will still work). And I am working on a feature/demo feature that may requires OpenCV manipulation and that's why I put it there at the beginning (you will why you need OpenCV when you do archiving).

For the model, feel free to change it and as I mentioned [here](https://github.com/KleinYuan/Caffe2-iOS/issues/8) and [here](https://github.com/KleinYuan/Caffe2-iOS/wiki#scope), I am working on adding more models rather than squeezeNet (and I will be happy to see some contributions as well).

It's just currently, the models I tried to bring in have some memory limit issues to resolve. Hopefully I can get it done ASAP, lol.

**Comment by KleinYuan** [comment]
@Shoshin23 I think we can close this issue and if you have further questions we can reopen it.
